services:
  bookcatalog.api:
    image: bookcatalog.api
    build:
      context: .
      dockerfile: BookCatalog.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=BookCatalog;Username=postgres;Password=19042006
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: BookCatalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19042006
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: